services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile  # 修改這裡，從 context（專案根目錄）的角度指定路徑
    environment:
      - PHPFPM_HOST=${PHPFPM_HOST:-php-fpm}
      - PHPFPM_PORT=${PHPFPM_PORT:-9000}
    ports:
      - "80:80"
    volumes:
      - ../www:/var/www/html:cached
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: ..
      dockerfile: ./docker/php-fpm/Dockerfile  # 修改這裡，從 context（專案根目錄）的角度指定路徑
    volumes:
      - ../www:/var/www/html:cached
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
